version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ktor_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Postgres1
      POSTGRES_DB: ktor_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ktor_network

volumes:
  pgdata:

networks:
  ktor_network:
    external: true
